<?php

  $title = 'Usuń przychód';
  $this->headTitle($title);
?>
<h1>Potwierdź usunięcie:</h1>

<p>
    Kwota: <b><?php echo $this->escapeHtml($incomes->amount); ?></b><br />
    Kategoria: <b><?php echo $this->escapeHtml($incomes->category); ?></b><br />
    Data: <b><?php echo $this->escapeHtml($incomes->date); ?></b>
</p>
<?php
  $url = $this->url('incomes', array(
      'action' => 'delete',
      'id'     => $this->id,
  ));
?>
<form action="<?php echo $url; ?>" method="post">
  <div>
      <input type="hidden" name="id" value="<?php echo (int) $incomes->id; ?>" />
      <input type="submit" class="btn btn-default" name="del" value="Yes" />
      <input type="submit" class="btn btn-default" name="del" value="No" />
  </div>
</form>