<?php

  $title = 'Edytuj wydatek';
  $this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
  $form = $this->form;
  $form->setAttribute('action', $this->url(
      'outcomes',
      array(
          'action' => 'edit',
          'id'     => $this->id,
      )
  ));
  $form->prepare();

  echo $this->form()->openTag($form);
?>

<div class="form-group">
  <?php echo $this->formRow($form->get('amount')); ?>
</div>

<div class="form-group ui-widget">
  <?php echo $this->formRow($form->get('category')); ?>
</div>

<div class="form-group">
  <?php echo $this->formRow($form->get('date')); ?>
</div>

<?php
  echo $this->formSubmit($form->get('submit'));
  echo $this->form()->closeTag();