<div class="jumbotron">
    <h1>Zarządzanie finansami</h1>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Wydatki</h3>
            </div>
            <div class="panel-body">
                <p><a href="<?php echo $this->url('outcomes') ?>">Lista wydatków</a></p>
                <p><a class="btn btn-success pull-right" href="<?php echo $this->url('outcomes', array('action' => 'add')) ?>">Dodaj wydatek</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Przychody</h3>
            </div>
            <div class="panel-body">
                <p><a href="<?php echo $this->url('incomes') ?>">Lista przychodów</a></p>
                <p><a class="btn btn-success pull-right" href="<?php echo $this->url('incomes', array('action' => 'add')) ?>">Dodaj przychód</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Wykresy</h3>
            </div>
            <div class="panel-body">
                    <ul class="charts-menu">
                        <li><a href="">Wydatki według kategorii</a></li>
                        <li><a href="">Przychody według kategorii</a></li>
                        <li><a href="">Wydatki według dni</a></li>
                        <li><a href="">Przychody według dni</a></li>
                    </ul>
            </div>
        </div>
    </div>
</div>
